# Generated by Django 2.1.1 on 2018-09-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_teacher_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='age',
            field=models.IntegerField(blank=True, default=18, null=True, verbose_name='年龄'),
        ),
    ]
