# Generated by Django 2.1.1 on 2018-09-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_courseorg_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseorg',
            name='age',
        ),
        migrations.AddField(
            model_name='teacher',
            name='age',
            field=models.IntegerField(blank=True, default=18, null=True, verbose_name='年龄'),
        ),
    ]
