# Generated by Django 2.1.1 on 2018-09-17 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_coursecomments_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecomments',
            name='comments',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='评论'),
        ),
    ]
