# Generated by Django 2.1.1 on 2018-09-06 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20180906_1003'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseResources',
            new_name='CourseResource',
        ),
    ]
